module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        action: "var(--action)",
        "app-primary": "var(--app-primary)",
        "app-secondary": "var(--app-secondary)",
        "base-black": "var(--base-black)",
        baseblack: "var(--baseblack)",
        black: "var(--black)",
        "color-1": "var(--color-1)",
        "color-2": "var(--color-2)",
        "color-3": "var(--color-3)",
        "full-white": "var(--full-white)",
        "gray-border": "var(--gray-border)",
        "iconbrowser-controlslight": "var(--iconbrowser-controlslight)",
        "iconurl-controlsdisabledlight": "var(--iconurl-controlsdisabledlight)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "extension-body-text": "var(--extension-body-text-font-family)",
        "extension-button": "var(--extension-button-font-family)",
        "extension-h1": "var(--extension-h1-font-family)",
        "extension-h2": "var(--extension-h2-font-family)",
        "extension-h3": "var(--extension-h3-font-family)",
        "extension-headline": "var(--extension-headline-font-family)",
        "extension-label": "var(--extension-label-font-family)",
        "web-above-title": "var(--web-above-title-font-family)",
        "web-body-text": "var(--web-body-text-font-family)",
        "web-button": "var(--web-button-font-family)",
        "web-h1": "var(--web-h1-font-family)",
        "web-h2": "var(--web-h2-font-family)",
        "web-h3": "var(--web-h3-font-family)",
        "web-headline": "var(--web-headline-font-family)",
        "web-label": "var(--web-label-font-family)",
        "web-large": "var(--web-large-font-family)",
        "web-subheadline": "var(--web-subheadline-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        button: "var(--button)",
        "form-shadow": "var(--form-shadow)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
